apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  restartPolicy: Never
  containers:
    - name: cuda
      image: nvidia/cuda:12.3.2-base-ubuntu22.04
      command: ["bash", "-lc"]
      args:
        - |
          echo "=== Assigned GPU(s) (from device plugin) ==="
          echo "NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES}"
          echo "CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES}"
          echo
          echo "=== nvidia-smi -L (what the container can see) ==="
          nvidia-smi -L || true
          echo
          echo "=== nvidia-smi (detailed) ==="
          nvidia-smi || true
          echo
          echo "Sleeping so you can exec/log..."
          sleep 3600
      resources:
        limits:
          nvidia.com/gpu: 1