
# Install HashiCorp Vault via Helm (single-node, dev/test)
- name: Ensure kubernetes Python library is installed
  ansible.builtin.pip:
    name: kubernetes
    state: present
    executable: "{{ ansible_playbook_python | replace('/bin/python', '/bin/pip') }}"

- name: Install Helm if not present
  ansible.builtin.shell: |
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    creates: /usr/local/bin/helm
  become: true

- name: Install Vault CLI if not present
  ansible.builtin.shell: |
    wget -O- https://releases.hashicorp.com/vault/1.15.2/vault_1.15.2_linux_amd64.zip | gunzip > /usr/local/bin/vault
    chmod +x /usr/local/bin/vault
  args:
    creates: /usr/local/bin/vault
  become: true

- name: Add HashiCorp Helm repo
  ansible.builtin.shell: helm repo add hashicorp https://helm.releases.hashicorp.com
  changed_when: false

- name: Update Helm repos
  ansible.builtin.shell: helm repo update
  changed_when: false

- name: Create default namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ vault_namespace }}"
    state: present

# Install local-path-provisioner for persistent storage (if not present)
- name: Check if local-path-provisioner is installed
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    namespace: local-path-storage
    name: local-path-provisioner
  register: lpp_deploy
  failed_when: false

- name: Install local-path-provisioner if not present
  ansible.builtin.shell: |
    kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.26/deploy/local-path-storage.yaml
  when: lpp_deploy.resources | length == 0
  changed_when: true

# Write values.yaml for Vault (persistent mode only)
- name: Write values.yaml for Vault (persistent mode)
  copy:
    dest: /tmp/vault-values.yaml
    content: |
      server:
        image:
          repository: hashicorp/vault
          tag: "1.15.2"
        ha:
          enabled: false
        dataStorage:
          enabled: true
          size: 2Gi
          storageClass: local-path
        dev:
          enabled: false
        extraEnvironmentVars:
          VAULT_LOG_LEVEL: debug
        extraConfig: |
          ui = true

          listener "tcp" {
            tls_disable = 1
            address = "[::]:8200"
            cluster_address = "[::]:8201"
            telemetry {
              unauthenticated_metrics_access = "true"
            }
          }

          storage "file" {
            path = "/vault/data"
          }

          telemetry {
            prometheus_retention_time = "5m"
            disable_hostname = true
          }

          disable_mlock = true
      ui:
        enabled: true
      service:
        type: ClusterIP

- name: Install or upgrade Vault via Helm (persistent mode)
  ansible.builtin.shell: |
    helm upgrade --install vault hashicorp/vault --namespace {{ vault_namespace }} -f /tmp/vault-values.yaml
  register: vault_helm_install
  changed_when: vault_helm_install.rc == 0

- name: Ensure Vault configuration enables Prometheus telemetry
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: vault-config
        namespace: "{{ vault_namespace }}"
        labels:
          app.kubernetes.io/name: vault
          app.kubernetes.io/instance: vault
      data:
        extraconfig-from-values.hcl: |
          ui = true

          listener "tcp" {
            tls_disable = 1
            address = "[::]:8200"
            cluster_address = "[::]:8201"
            telemetry {
              unauthenticated_metrics_access = "true"
            }
          }

          storage "file" {
            path = "/vault/data"
          }

          telemetry {
            prometheus_retention_time = "5m"
            disable_hostname = true
          }

          disable_mlock = true

- name: Restart Vault pods to apply configuration changes
  ansible.builtin.command: kubectl delete pod -l app.kubernetes.io/name=vault -n {{ vault_namespace }} --ignore-not-found
  register: vault_pod_delete
  changed_when: vault_pod_delete.rc == 0
  failed_when: vault_pod_delete.rc not in [0, 1]

- name: Wait for Vault pod to be running
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    namespace: "{{ vault_namespace }}"
    label_selectors:
      - "app.kubernetes.io/name=vault"
  register: vault_pod_info
  until: vault_pod_info.resources | length > 0 and vault_pod_info.resources[0].status.phase == "Running"
  retries: 30
  delay: 10

- name: Additional wait for Vault to stabilize
  ansible.builtin.pause:
    seconds: 5

- name: Port-forward Vault service for initialization
  ansible.builtin.shell: |
    nohup kubectl port-forward -n {{ vault_namespace }} svc/vault 8200:8200 > /tmp/vault-portforward.log 2>&1 &
    echo $! > /tmp/vault-portforward.pid
    sleep 10
  register: port_forward_start

- name: Initialize Vault
  ansible.builtin.shell: |
    rm -f /root/vault-init.json
    export VAULT_ADDR=http://localhost:8200
    vault operator init -key-shares=1 -key-threshold=1 -format=json > /root/vault-init.json
    chmod 644 /root/vault-init.json
  environment:
    VAULT_ADDR: http://localhost:8200
  register: vault_init
  until: vault_init.rc == 0
  retries: 10
  delay: 5
  become: true

- name: Unseal Vault
  ansible.builtin.shell: |
    export VAULT_ADDR=http://localhost:8200
    vault operator unseal $(jq -r '.unseal_keys_b64[0]' /root/vault-init.json)
  environment:
    VAULT_ADDR: http://localhost:8200
  become: true
  register: vault_unseal
  until: vault_unseal.rc == 0
  retries: 5
  delay: 3

- name: Wait for Vault pod to be ready (after unseal)
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    namespace: "{{ vault_namespace }}"
    label_selectors:
      - "app.kubernetes.io/name=vault"
    wait: true
    wait_condition:
      type: Ready
      status: "True"
    wait_timeout: 120

- name: Create /root/.vault-token from root token
  ansible.builtin.shell: |
    jq -r '.root_token' /root/vault-init.json > /root/.vault-token
    chmod 600 /root/.vault-token
  become: true

# (No longer needed: vault-init.json is created directly in /root)

- name: Show Vault usage instructions
  debug:
    msg:
      - "Vault is initialized and unsealed (persistent mode, file storage)."
      - "Root token is in /root/vault-init.json (key: .root_token)."
      - "To port-forward for local access:"
      - "  ./library/start_portforward.sh vault 8200 {{ vault_namespace }} /tmp/vault-portforward.log /tmp/vault-portforward.pid"
      - "To use the Vault CLI, run:"
      - "  export VAULT_TOKEN=$(sudo jq -r '.root_token' /root/vault-init.json)"
      - "  export VAULT_ADDR=http://vault.default.svc.cluster.local:8200"
      - "  export VAULT_ADDR=http://localhost:8200"
      - "  vault status"
      - "  vault login"
      - "UI: http://vault.default.svc.cluster.local:8200/ui"